DELETE
FROM public.artists
WHERE name IN ('Ahmed Aldoori',
               'Alex Heath',
               'Alexandra Frantseva',
               'Arash Radkia',
               'Armand Serrano',
               'Aron Elekes',
               'Arthur Bozonnet',
               'Ben Maier',
               'Brandon Liao',
               'Brian Valeza',
               'Carlos Ruiz',
               'Chris Anyma',
               'David Cserktui',
               'David Kegg',
               'Devin Law',
               'Dmitry Klyushkin',
               'Frankie Perez',
               'Halil Ural',
               'Izzy',
               'Jana Schirmer',
               'John Donahue',
               'John Thacker',
               'Kudaman',
               'Maria Poliakova',
               'Mooncolony',
               'Mushk Rizvi',
               'Pablo Carpio',
               'Piero Vianello',
               'Quentin de Warren',
               'Quentin Regnes',
               'Robert Kim',
               'Room 8 Studio',
               'Rudy Siswanto',
               'Sam Burley',
               'Thomas Chamberlain-Keen',
               'Tomas Muir',
               'Wangjie Li',
               'Wayne Wu',
               'Yangtian Li',
               'Zinna Du',
               'Zoltan Boros');

